### ISSUE TITLE
Several questions about Reg_DOMD.py

### ISSUE THREAD

**Issue by k2022-wen** [liumy2010/LiteEFG#1]
1. “ev” and  “bar_ev” are defined with parameter “is_static=True” in backward, which means they are updated at initialization. But “ev” can be updated in function get_ev. How should I understand this definition?

2.For player x, is “self.utility” the direct components with size  action_set_size of Ay or a vector computed in bottom-up manner with the equality in Lemma 1 and Lemma 2 of the paper "Last-iterate Convergence in Extensive-Form Games"？

3. In function 'update', I write the process of the update of “u” and “bar_u”, which is different from the first equality presented in Lemma 1 and Lemma 2 of paper “Last-iterate Convergence in Extensive-Form Games”.  I don’t know where I made a mistake. Could you please make some simple notes if it’s possible or recommend me several references that are easy to understand?

4.  In 'with LiteEFG.backward()', Is the update principle that all the variables of the same information set have been updated before the variables of the next information set update in bottom-up manner? Why are "get_ev" updated after "_update"?

5. In 'with LiteEFG.backward(color=0):' variables 'bar_gradient' and 'gradient' are computed with the same 'self.utility', then they are prepared to update \hat z{t+1} and z_{t+1} at the same time as they use the same 'self.utility'.  \hat z{t+1} and z_{t} use different 'self.utility'. However, the initialization is z_0 = \hat z _1. I don't where I made a mistake.

**Comment by liumy2010** [comment]
1. At backward(is_static=True), the variables are created and initialized. Then, the variables are updated in get_ev.
2. For each infoset, self.utility stores the slice of $Ay$ in that infoset.
3. May you post your code here so that I can have a better understanding of the issue?
4. You are right. LiteEFG will visit infosets in backward / forward order in each update. Once an infoset is visited, its computation graph will be fully executed so that all variables will be updated. _get_ev is after _update because the algorithm is mirror descent so we need the latest strategy to compute the feedback. [1] would be a good reference to understand it.
5. Thank you for pointing out! The code here is a bit different from the paper at initialization. The code actually initialize $z_0=\hat z_0$, and update $\hat z_t, z_t$ at each iteration, since this is more computationally efficient.

[1] Lee, C. W., Kroer, C., & Luo, H. (2021). Last-iterate convergence in extensive-form games. Advances in Neural Information Processing Systems, 34, 14293-14305.

**Comment by k2022-wen** [comment]
Thank for your reply and recommendation. The reply helped me a lot! I have another two questions.
1. Is "ev" equal to what's inside the parentheses when computing "L_i" in Lemma 1 of [1]? I'm confused how to get the update of "ev" and "bar_ev" in Reg_DOMD.py.  Why is there a  "+ LiteEFG.euclidean(ref_strategy) * self.coef)" or "- LiteEFG.euclidean(strategy) * self.coef)" in the  function "get_ev" when "Euclidean"?  I find it difficult to get the same results.

2. In  [1],  when \Phi is negative entropy in Lemma 1, is it equivalent to Lemma 2?

[1] Lee, C. W., Kroer, C., & Luo, H. (2021). Last-iterate convergence in extensive-form games. Advances in Neural Information Processing Systems, 34, 14293-14305.

**Comment by liumy2010** [comment]
1. ev is equal to the terms in the parentheses. It is the additional regularization term, which is not included in the update-rule of [1]. The implementation of [1] can be found in baselines/DOMD.py
2. Yes.

[1] Lee, C. W., Kroer, C., & Luo, H. (2021). Last-iterate convergence in extensive-form games. Advances in Neural Information Processing Systems, 34, 14293-14305.
